version: '3'

networks:
  mall:
    external: true
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    networks:
      - default
      - mall
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ~/mydata/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
    networks:
      - default
      - mall
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    volumes:
      - ~/mydata/nginx/conf:/etc/nginx #配置文件挂载
      - ~/mydata/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - ~/mydata/nginx/log:/var/log/nginx #日志文件挂载
    ports:
      - 80:80
    networks:
      - default
      - mall
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    volumes:
      - ~/mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ~/mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
      - mall
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ~/mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ~/mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
      - mall
  logstash:
    image: logstash:7.17.3
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ~/mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
    networks:
      - default
      - mall
  kibana:
    image: kibana:7.17.3
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
    networks:
      - default
      - mall
  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      - ~/mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
    networks:
      - default
      - mall
  nacos-registry:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos-registry
    environment:
      - "MODE=standalone"
    ports:
      - 8848:8848
    networks:
      - default
      - mall
  minio:
    container_name: minio
    image: bitnami/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9010:9001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/mydata/minio/data:/data
    networks:
      - default
      - mall