version: '3'

networks:
  mall:
    external: true
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.33.4
    volumes:
      - ~/mydata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/mydata/prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - default
      - mall
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
      - redis:redis
      - rabbitmq:rabbit
      - mongo:mongo
  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    volumes:
      - ~/mydata/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - default
      - mall
    external_links:
      - prometheus:prometheus
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.23.0
    volumes:
      - ~/mydata/prometheus/alertmanager:/alertmanager
    ports:
      - 9093:9093
    networks:
      - default
      - mall
  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway:v1.3.1
    volumes:
      - ~/mydata/prometheus/pushgateway:/var/lib/pushgateway
    ports:
      - 9091:9091
    networks:
      - default
      - mall
  mysql_exporter:
    container_name: mysql_exporter
    image: prom/mysqld-exporter:latest
    command:
      - "--mysqld.username=root:root"
      - "--mysqld.address=db:3306"
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.innodb_metrics'
      - '--collect.info_schema.tablestats'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.userstats'
      - '--collect.engine_innodb_status'
    external_links:
      - mysql:db
    ports:
      - 9104:9104
    networks:
      - default
      - mall
  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - 9121:9121
    networks:
      - default
      - mall