global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'dashboard'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'nacos'
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['nacos-registry:8848']
  - job_name: 'mysql'
    static_configs:
      - targets: [ 'mysql_exporter:9104']
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis_exporter:9121']